package com.realestate.app.enums;

public enum CityLocation {
	BERAT, BULQIZE, DELVINE, DEVOLL, DIBER, DURRES, ELBASAN, FIER, GRAMSH, GJIROKASTER, 
	HAS, KAVAJE, KOLONJE, KORCE, KRUJE, KUCOVE, KUKES, KURBIN, LEZHE, LIBRAZHD, LUSHNJE, 
	MALESIEMADHE, MALLAKASTER, MAT, MIRDITEM, PEQIN, PERMET, POGRADEC, PUKE, SARANDE, SKRAPAR,
	SHKODER, TEPELENE, TIRANE, TROPOJE, VLORE;
}
